name: GitHub Actions Check Before PR
on:
  push:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check and Build
      run: |
        npm install
        make config env=local
        make run-test
        make build
